services:
  logs-server:
    build:
      context: .
      dockerfile: LogsServer/Dockerfile
    container_name: logs-server-container
    networks:
      - obl-network
    ports:
      - "5001:5001"
    restart: "no"

  server:
    build:
      context: .
      dockerfile: Server/Dockerfile
    container_name: server-container
    networks:
      - obl-network
    volumes:
      - ./Server/Images:/app/Images   # accede a imágenes desde host
      - ./Server/database.txt:/app/database.txt  # persistencia de datos
    ports:
      - "20000:20000"
    stdin_open: true
    tty: true
    environment:
      - SERVER_IP=0.0.0.0             # escucha en todas las interfaces dentro del contenedor
      - SERVER_PORT=20000
      - SERVER_IMAGE_DIRECTORY=/app/Images
    entrypoint: ["sleep", "infinity"]  # Sobrescribe ENTRYPOINT del Dockerfile
    restart: "no"

  client1:
    build:
      context: .
      dockerfile: Client/Dockerfile
    container_name: client1
    networks:
      - obl-network
    stdin_open: true
    tty: true
    environment:
      - SERVER_IP=server     # nombre del servicio (resuelto por Docker DNS)
      - SERVER_PORT=20000
      - CLIENT_IP=0.0.0.0
      - CLIENT_PORT=0
    entrypoint: ["sleep", "infinity"]
    depends_on:
      - server
    restart: "no"

  client2:
    build:
      context: .
      dockerfile: Client/Dockerfile
    container_name: client2
    networks:
      - obl-network
    stdin_open: true
    tty: true
    environment:
      - SERVER_IP=server     # nombre del servicio (resuelto por Docker DNS)
      - SERVER_PORT=20000
      - CLIENT_IP=0.0.0.0
      - CLIENT_PORT=0
    entrypoint: ["sleep", "infinity"]
    depends_on:
      - server
    restart: "no"

networks:
  obl-network:
    driver: bridge
